name: Markdown CI

# https://github.com/gaurav-nelson/github-action-markdown-link-check

on:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  check-links:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
            use-quiet-mode: 'yes'
            use-verbose-mode: 'yes'
            max-depth: 2
